import { useParams } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { Save, Sparkles, Check } from "lucide-react";
import { api, type Endpoint } from "@/lib/api";
import { MethodBadge, EndpointsEmpty } from "./EndpointsPage";
import { cn } from "@/lib/utils";

export function EndpointDetailPage() {
  const { id = "" } = useParams<{ id: string }>();
  const qc = useQueryClient();

  const { data: ep, isLoading } = useQuery({
    queryKey: ["endpoint", id],
    queryFn: () => api.getEndpoint(id),
  });

  const [notes, setNotes] = useState("");
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    if (ep) setNotes(ep.ai_notes ?? "");
  }, [ep]);

  const update = useMutation({
    mutationFn: (patch: Partial<Endpoint>) => api.updateEndpoint(id, patch),
    onSuccess: (u) => {
      qc.setQueryData(["endpoint", id], u);
      qc.invalidateQueries({ queryKey: ["endpoints"] });
      setSaved(true);
      setTimeout(() => setSaved(false), 1400);
    },
  });

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center text-xs text-muted-foreground">
        Loading…
      </div>
    );
  }
  if (!ep) return <EndpointsEmpty />;

  const dirty = notes !== (ep.ai_notes ?? "");

  return (
    <div className="flex h-full flex-col">
      <header className="border-b border-border px-6 py-4">
        <div className="flex items-center gap-2 text-[11px] text-muted-foreground">
          <span className="mono">{ep.app}</span>
          <span>·</span>
          <span>{ep.view}</span>
          <span>·</span>
          <span>
            scanned{" "}
            {new Date(ep.last_scanned).toLocaleString(undefined, {
              month: "short",
              day: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            })}
          </span>
        </div>
        <div className="mt-2 flex items-center gap-3">
          <MethodBadge method={ep.method} />
          <code className="mono truncate text-base font-medium text-foreground">
            {ep.path}
          </code>
        </div>
      </header>

      <div className="min-h-0 flex-1 overflow-y-auto px-6 py-5">
        <div className="mx-auto max-w-3xl space-y-6">
          <div className="grid grid-cols-3 gap-3">
            <MetaCard label="Method" value={ep.method} mono />
            <MetaCard label="View" value={ep.view} mono />
            <MetaCard label="App" value={ep.app} mono />
          </div>

          <section className="rounded-lg border border-ai/25 bg-ai/[0.04] p-4">
            <div className="flex items-start justify-between gap-3">
              <div className="flex items-center gap-2">
                <span className="flex h-6 w-6 items-center justify-center rounded-md bg-ai/15 ring-1 ring-ai/30">
                  <Sparkles className="h-3 w-3 text-ai" strokeWidth={2.5} />
                </span>
                <div>
                  <h3 className="text-xs font-semibold text-foreground">
                    AI-drafted notes
                  </h3>
                  <p className="text-[10px] text-muted-foreground">
                    Generated by DevLens · fully editable · treat as a starting
                    point
                  </p>
                </div>
              </div>
              <button
                onClick={() => update.mutate({ ai_notes: notes })}
                disabled={!dirty || update.isPending}
                className={cn(
                  "inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium transition",
                  dirty
                    ? "bg-primary text-primary-foreground hover:opacity-90"
                    : "bg-surface text-muted-foreground",
                )}
              >
                {saved ? (
                  <>
                    <Check className="h-3.5 w-3.5" /> Saved
                  </>
                ) : (
                  <>
                    <Save className="h-3.5 w-3.5" />
                    {update.isPending ? "Saving…" : dirty ? "Save" : "Saved"}
                  </>
                )}
              </button>
            </div>

            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={10}
              placeholder="No notes yet. Trigger a Scan or write your own."
              className="input mt-3 bg-background/40"
            />

            {ep.ai_notes_generated_at && (
              <p className="mt-2 text-[10px] text-muted-foreground">
                Draft generated{" "}
                {new Date(ep.ai_notes_generated_at).toLocaleString()}
              </p>
            )}
          </section>
        </div>
      </div>
    </div>
  );
}

function MetaCard({
  label,
  value,
  mono,
}: {
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div className="rounded-md border border-border bg-surface p-3">
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">
        {label}
      </div>
      <div
        className={cn(
          "mt-1 truncate text-sm font-medium text-foreground",
          mono && "mono",
        )}
      >
        {value}
      </div>
    </div>
  );
}
